name: "Setup UDS CLI"

on:
  schedule:
    - cron: "0 4 * * *"
  pull_request:
  push:
    branches:
      - main

jobs:
  test-defaults:
    name: Defaults config test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup UDS CLI with defaults
        uses: ./

      - name: Verify UDS CLI version
        run: uds version

  setup-uds:
    name: Full test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup UDS CLI
        uses: ./
        with:
          # renovate: datasource=github-tags depName=defenseunicorns/uds-cli versioning=semver
          version: v0.20.0

      - name: UDS CLI Version
        run: uds version

      - name: Install k3d
        run: |
          curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
          k3d cluster delete && k3d cluster create

      - name: Deploy test bundle in dev mode
        run: uds dev deploy ghcr.io/defenseunicorns/packages/uds-cli/test/publish/ghcr-test:0.0.1

      - name: List installed packages
        run: uds zarf package list

  test-error-version:
    name: Verify error on bad/unavailable version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup UDS CLI with defaults
        id: error_step
        uses: ./
        with:
          version: v0.01.9
        continue-on-error: true  # Allow the workflow to continue after failure

      - name: The demo step has failed
        if: ${{ always() }}
        shell: bash
        run: |
          #!/bin/bash
          if [ "${{ steps.error_step.outcome }}" != "failure" ]; then
            echo "Expected the step to fail, but it did not!"
            exit 1
          else
            echo "The step failed as expected."
          fi
