name: "Setup UDS CLI"

on:
  schedule:
    - cron: "0 4 * * *"
  pull_request:
  push:
    branches:
      - main

jobs:
  test-defaults:
    name: Defaults config test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup UDS CLI with defaults
        uses: ./

      - name: Verify UDS CLI version
        run: uds version

  setup-uds:
    name: Full test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup UDS CLI
        uses: ./
        with:
          # renovate: datasource=github-tags depName=defenseunicorns/uds-cli extractVersion="^v(.*)$" versioning=semver-coerced
          version: v0.16.0

      - name: UDS CLI Version
        run: uds version

      - name: Install k3d
        run: |
          curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
          k3d cluster delete && k3d cluster create

      - name: Deploy test bundle in dev mode
        run: uds dev deploy ghcr.io/defenseunicorns/packages/uds-cli/test/publish/ghcr-test:0.0.1

      - name: List installed packages
        run: uds zarf package list
